#!/usr/bin/env bash
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# Create OEL9 HCI VMs on vCenter (vc01.vmalpha.com) via govc.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT_INVENTORY="${SCRIPT_DIR}/inventory.ini"

: "${GOVC_URL:?Set GOVC_URL, e.g. https://vc01.vmalpha.com}"
: "${GOVC_USERNAME:?Set GOVC_USERNAME}"
: "${GOVC_PASSWORD:?Set GOVC_PASSWORD}"
: "${GOVC_DATACENTER:?Set GOVC_DATACENTER}"
: "${GOVC_DATASTORE:?Set GOVC_DATASTORE}"
: "${GOVC_NETWORK:?Set GOVC_NETWORK}"

OEL9_TEMPLATE="${OEL9_TEMPLATE:-OEL9-Base}"
GOVC_FOLDER="${GOVC_FOLDER:-cloudstack-hci}"
GOVC_INSECURE="${GOVC_INSECURE:-true}"
HCI_SSH_PUBLIC_KEY="${HCI_SSH_PUBLIC_KEY:-${HOME}/.ssh/id_rsa.pub}"
NODE_COUNT="${NODE_COUNT:-3}"
MGMT_NAME="${MGMT_NAME:-hci-mgmt}"
NODE_PREFIX="${NODE_PREFIX:-hci-node}"

export GOVC_INSECURE

if ! command -v govc >/dev/null 2>&1; then
  echo "govc is required: https://github.com/vmware/govmomi/tree/master/govc" >&2
  exit 1
fi

if [[ ! -f "${HCI_SSH_PUBLIC_KEY}" ]]; then
  echo "SSH public key not found: ${HCI_SSH_PUBLIC_KEY}" >&2
  exit 1
fi

echo "==> Checking vCenter connectivity: ${GOVC_URL}"
govc about

echo "==> Ensuring folder /${GOVC_DATACENTER}/vm/${GOVC_FOLDER}"
govc folder.create "/${GOVC_DATACENTER}/vm/${GOVC_FOLDER}" 2>/dev/null || true

clone_vm() {
  local name="$1"
  local cpus="$2"
  local mem_mb="$3"
  local extra_disk_gb="${4:-0}"

  if govc vm.info -json "${name}" >/dev/null 2>&1; then
    echo "VM ${name} already exists, skipping clone"
  else
    echo "==> Cloning ${OEL9_TEMPLATE} -> ${name}"
    local pool_args=()
    if [[ -n "${GOVC_CLUSTER:-}" ]]; then
      pool_args=(-cluster "${GOVC_CLUSTER}")
    elif [[ -n "${GOVC_RESOURCE_POOL:-}" ]]; then
      pool_args=(-pool "${GOVC_RESOURCE_POOL}")
    fi
    govc vm.clone \
      -vm "${OEL9_TEMPLATE}" \
      -ds "${GOVC_DATASTORE}" \
      -folder "/${GOVC_DATACENTER}/vm/${GOVC_FOLDER}" \
      -on=false \
      "${pool_args[@]}" \
      "${name}"
  fi

  govc vm.change -vm "${name}" -c "${cpus}" -m "${mem_mb}"
  # Nested virtualization for KVM-in-VM labs
  govc vm.change -vm "${name}" -e "vhv.enable=TRUE" -e "disk.enableUUID=TRUE"

  if [[ "${extra_disk_gb}" -gt 0 ]]; then
    local disks
    disks="$(govc device.ls -vm "${name}" | awk '/disk-/ {print $1}' | wc -l | tr -d ' ')"
    if [[ "${disks}" -lt 2 ]]; then
      echo "==> Adding ${extra_disk_gb}g OSD disk to ${name}"
      govc vm.disk.create -vm "${name}" -name "${name}-osd" -size "${extra_disk_gb}G"
    fi
  fi

  # Inject SSH key via guestinfo when cloud-init / Ignition is present on template.
  # Also store for operators who use guest customization.
  if [[ -f "${HCI_SSH_PUBLIC_KEY}" ]]; then
    local pubkey
    pubkey="$(cat "${HCI_SSH_PUBLIC_KEY}")"
    govc vm.change -vm "${name}" \
      -e "guestinfo.userdata.encoding=base64" \
      -e "guestinfo.metadata.encoding=base64" 2>/dev/null || true
    # Prefer cloud-init #cloud-config if template supports it
    local ud
    ud="$(printf '#cloud-config\nusers:\n  - name: opc\n    sudo: ALL=(ALL) NOPASSWD:ALL\n    ssh_authorized_keys:\n      - %s\n  - name: root\n    ssh_authorized_keys:\n      - %s\nssh_pwauth: false\n' "${pubkey}" "${pubkey}" | base64 | tr -d '\n')"
    govc vm.change -vm "${name}" -e "guestinfo.userdata=${ud}" 2>/dev/null || true
  fi

  govc vm.network.change -vm "${name}" -net "${GOVC_NETWORK}" ethernet-0 2>/dev/null || true
  govc vm.power -on "${name}"
}

clone_vm "${MGMT_NAME}" 4 16384 0
for i in $(seq 1 "${NODE_COUNT}"); do
  clone_vm "${NODE_PREFIX}${i}" 8 32768 200
done

echo "==> Waiting for guest IPs (VMware Tools required on OEL9 template)..."
declare -A IPS
ALL_VMS=("${MGMT_NAME}")
for i in $(seq 1 "${NODE_COUNT}"); do
  ALL_VMS+=("${NODE_PREFIX}${i}")
done

for attempt in $(seq 1 60); do
  ready=true
  for vm in "${ALL_VMS[@]}"; do
    ip="$(govc vm.ip -v4 -wait=5s "${vm}" 2>/dev/null || true)"
    if [[ -z "${ip}" ]]; then
      ready=false
    else
      IPS["${vm}"]="${ip}"
    fi
  done
  if ${ready}; then
    break
  fi
  echo "  attempt ${attempt}/60: still waiting for IPs..."
  sleep 10
done

{
  cat <<EOF
# Generated by govc-create-vms.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)
# vCenter: ${GOVC_URL}

[hci_mgmt]
EOF
  echo "${MGMT_NAME} ansible_host=${IPS[${MGMT_NAME}]:-CHANGE_ME} ansible_user=opc ansible_become=true"

  echo
  echo "[hci_nodes]"
  for i in $(seq 1 "${NODE_COUNT}"); do
    name="${NODE_PREFIX}${i}"
    echo "${name} ansible_host=${IPS[${name}]:-CHANGE_ME} ansible_user=opc ansible_become=true"
  done

  cat <<EOF

[hci:children]
hci_mgmt
hci_nodes

[hci:vars]
ansible_ssh_private_key_file=${HCI_SSH_PRIVATE_KEY:-${HOME}/.ssh/id_rsa}
ceph_public_network=0.0.0.0/0
cloudstack_repo_base=https://download.apache.org/cloudstack/releases
EOF
} > "${OUT_INVENTORY}"

echo
echo "Wrote ${OUT_INVENTORY}"
echo "Next: ansible-playbook -i inventory.ini ansible/site.yml"
for vm in "${ALL_VMS[@]}"; do
  echo "  ${vm} -> ${IPS[${vm}]:-pending}"
done
